theme: jekyll-theme-slate
title: Welcome to Dietrich's GitHub!!
description: Feel free to bookmark this page and follow (or join) my projects!

# Disable plugins that require network access
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub metadata
repository: Djeppschmidt/DJEppSchmidt.github.io
github: [metadata]
