theme: jekyll-theme-modernist
title: Humane Ecology
description: Scientific rigor, analytic acuity, infrastructure to make a difference.

# Disable plugins that require network access
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub metadata
repository: Djeppschmidt/HumaneEcology.github.io
github: [metadata]
